---
fixtures:
  repositories:
    # iptables:
    #   repo: https://github.com/simp/pupmod-simp-iptables
    #   ref: 6.0.1
    etcd:
      repo: https://github.com/cristifalcas/puppet-etcd
      # patch made upstream 
      ref: 9e3bf7f71c2ad3d91351068a51d5db06ff8763fe
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      ref: 3.3.1
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
      ref: 4.19.1
