---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9380
  selector:
    app: nginx
